name: Unit Tests
permissions: {}

on: [push]
jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: markdown-check
        run: |
          python -m pymarkdown -d MD013,MD033,MD034 scan .
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: code-check
        run: |
          python -m pytest -c pytest.checks.ini
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: isort
        run: |
          python -m isort --check-only --diff .
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Code Format
        run: |
          python -m black --check --diff --color -S .
  pytest:
    needs: [isort, lint, code-check, markdown-check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
          pip install -e .[all]
          git clone https://github.com/openvinotoolkit/nncf.git /tmp/nncf
          cd /tmp/nncf && git checkout e0bc50359992a3d73d4ed3e6396c8b4f1d4ae631 && pip install -e .
      - name: Test with pytest
        run: |
          python -m pytest -v --cov dynast/ --cov-report html --cov-report term
      - name: Archive test coverage
        uses: actions/upload-artifact@v2
        if: ${{ success() }}
        with:
          name: tests-coverage-py${{ matrix.python-version }}
          path: |
            htmlcov
          retention-days: 7
